find_library(CBLAS_satlas_LIBRARY NAMES satlas)
find_library(CBLAS_atlas_LIBRARY NAMES atlas)
find_library(CBLAS_cblas_LIBRARY NAMES cblas)
find_library(CBLAS_blas_LIBRARY NAMES blas)

set(CBLAS_LIBRARIES "-NOTFOUND")
if(CBLAS_cblas_LIBRARY AND CBLAS_blas_LIBRARY)
    set(CBLAS_LIBRARIES "${CBLAS_cblas_LIBRARY}" "${CBLAS_blas_LIBRARY}")
endif()
if(CBLAS_cblas_LIBRARY AND CBLAS_atlas_LIBRARY)
    set(CBLAS_LIBRARIES "${CBLAS_cblas_LIBRARY}" "${CBLAS_atlas_LIBRARY}")
endif()
if(CBLAS_satlas_LIBRARY)
    set(CBLAS_LIBRARIES "${CBLAS_satlas_LIBRARY}")
endif()

if(CBLAS_LIBRARIES)
    message("CBLAS: ${CBLAS_LIBRARIES}")
else()
    message("CBLAS not found")
endif()
